#include <iostream>
#include <cstdint>

// MLIR's memory wrapper struct
template <typename T, int N> struct MemRefDescriptor {
  T *allocated;
  T *aligned;
  intptr_t offset;
  intptr_t sizes[N];
  intptr_t strides[N];
};

// The C-interface function generated by the --llvm-request-c-wrappers flag
extern "C" void _mlir_ciface_forward(MemRefDescriptor<int, 2> *output, 
                                     MemRefDescriptor<int, 2> *inputA, 
                                     MemRefDescriptor<int, 2> *inputB);

int main() {
    // 1. Allocate raw memory arrays for 2x2 matrices
    int a_data[4] = {1, 2, 3, 4};
    int b_data[4] = {10, 20, 30, 40};
    int out_data[4] = {0, 0, 0, 0};

    // 2. Wrap arrays in MemRef structs
    // Shape is {2, 2} and Strides are {2, 1}
    MemRefDescriptor<int, 2> A = {a_data, a_data, 0, {2, 2}, {2, 1}};
    MemRefDescriptor<int, 2> B = {b_data, b_data, 0, {2, 2}, {2, 1}};
    MemRefDescriptor<int, 2> Out = {out_data, out_data, 0, {2, 2}, {2, 1}};

    // 3. Execute the compiled MLIR model
    _mlir_ciface_forward(&Out, &A, &B);

    // 4. Print the resulting addition
    std::cout << "Computed Result:" << std::endl;
    std::cout << "[" << Out.aligned[0] << ", " << Out.aligned[1] << "]" << std::endl;
    std::cout << "[" << Out.aligned[2] << ", " << Out.aligned[3] << "]" << std::endl;
    
    return 0;
}